services:
  - type: web
    name: zivotopiscore
    runtime: docker
    repo: https://github.com/Rubin1977/zivotopis-core
    branch: main
    dockerfilePath: Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        value: Host=dpg-d4avu0c9c44c738r1q30-a;Port=5432;Database=zivotopisdb;Username=zivotopisuser;Password=lKUPaGjmH4gGYM4cMsnfgoM4tBKlrwUl
      - key: DatabaseProvider
        value: PostgreSQL

